######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 4 13:23:56 2008
######################################################################

TEMPLATE = lib
CONFIG   = staticlib
CONFIG  -= qt 
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
OBJECTS_DIR = obj
# Input
HEADERS += bg.h \
           bgmatrix.h \
           BNodeList.h \
           chromosome.h \
           data.h \
           datanode.h \
           dblock.h \
           disequilHMM.h \
           doublematrix.h \
           exception.h \
           field.h \
           fieldstruct.h \
           fpmm.h \
           geneticdist.h \
           genome.h \
           glmm.h \
           gnodederived.h \
           gnodesetderived.h \
           gnodestuff.h \
           hashtable.h \
           histogram.h \
           IBDMatrix.h \
           individual.h \
           matrix.h \
           matrixwbg.h \
           MersenneTwister.h \
           mim.h \
           minimizer.h \
           model.h \
           mqtl.h \
           nufamily.h \
           parmMap.h \
           pedigree.h \
           plotter.h \
           population.h \
           pt.h \
           regexp.h \
           rpedigree.h \
           rsamplerparms.h \
           rutil.h \
           safe_vectors.h \
           session.h \
           sparsebgmatrix.h \
           sparsematrix.h \
           stat.h \
           statdist.h \
           statdistbase.h \
           termlist.h \
           util.h \
           vector.h
SOURCES += alleletrim.cpp \
           bg.cpp \
           bgmatrix.cpp \
           BNodeList.cpp \
           chromosome.cpp \
           data.cpp \
           datanode.cpp \
           dblock.cpp \
           doublematrix.cpp \
           field.cpp \
           fieldstruct.cpp \
           fpmm.cpp \
           geneticdist.cpp \
           genome.cpp \
           ginverse1.cpp \
           glmm1.cpp \
           glmm2.cpp \
           gnodederived.cpp \
           gnodestuff.cpp \
           hashtable.cpp \
           histogram.cpp \
           IBDMatrix.cpp \
           individual.cpp \
           maternalPaternal.cpp \
           mim.cpp \
           min_nr_powell.cpp \
           min_praxis.cpp \
           model.cpp \
           model_blup.cpp \
           model_gibbs.cpp \
           model_hypo.cpp \
           model_peeling.cpp \
           model_vce.cpp \
           mqtl.cpp \
           nonsymm_eigen.cpp \
           nufamily.cpp \
           parmMap.cpp \
           pedigree.cpp \
           plotter.cpp \
           pop_bayes.cpp \
           pop_gibbs.cpp \
           pop_graph.cpp \
           pop_mblup.cpp \
           pop_peeling.cpp \
           popMIM.cpp \
           population.cpp \
           population1.cpp \
           rpedigree.cpp \
           rsamplerparms.cpp \
           rutil.cpp \
           session.cpp \
           sparsebgmatrix.cpp \
           sparsematrix.cpp \
           stat1.cpp \
           stat2.cpp \
           statdist.cpp \
           symm_eigen.cpp \
           termlist.cpp \
           util.cpp
